collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7062476
  brandStrength: 1
  lightness: 0.7383116
  brandColors:
    - '#777F92'
    - '#D7E0EA'
    - '#B4BECE'
    - '#88765C'
  rhythmicContrast: 0.1476033
typography_spectrum: 0.5776583
layout_spectrum: 0.7520908
name: Krissy.TV
