name: Krissy.TV
favicon: null
layout_spectrum: 0.7520908
typography_spectrum: 0.5776583
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Krissy.TV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#322c28'
    - '#387e90'
    - '#00553d'
    - '#009e80'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
