name: Krissy.TV
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63455
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Krissy.TV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ca2c25'
    - '#2d4e25'
    - '#919191'
    - '#df6625'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
